CREATE TABLE IF NOT EXISTS public.click_event
(
    clicked_at
    timestamp
(
    6
) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
(
    INCREMENT
    1
    START
    1
    MINVALUE
    1
    MAXVALUE
    9223372036854775807
    CACHE
    1
),
    url_id bigint NOT NULL,
    ip_address character varying
(
    255
) COLLATE pg_catalog."default",
    referrer character varying
(
    255
) COLLATE pg_catalog."default",
    user_agent character varying
(
    255
) COLLATE pg_catalog."default",
    CONSTRAINT click_event_pkey PRIMARY KEY
(
    id
),
    CONSTRAINT fkcob7nxkgucdawl6vrgbf91pja FOREIGN KEY
(
    url_id
)
    REFERENCES public.url
(
    id
) MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
    )